# Derived from Data On EKS under Apache License 2.0.
# Source: https://github.com/awslabs/data-on-eks/tree/main/ai-ml/jupyterhub
# See LICENSE file in the root directory of this source code or at http://www.apache.org/licenses/LICENSE-2.0.html.
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: {{ .Values.name }}
spec:
  template:
    metadata:
      labels:
        NodePool: {{ .Values.name }}
        NodeGroupType: {{ .Values.name }}
        hub.jupyter.org/node-purpose: user
    spec:
      nodeClassRef:
        name: {{ .Values.name }}
      {{- with .Values.taints }}
      taints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      requirements:
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          {{- with .Values.instanceFamilies }}
          values:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - key: "karpenter.k8s.aws/instance-size"
          operator: In
          {{- with .Values.instanceSizes }}
          values:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: 
              - {{ .Values.capacityTypes }}
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
    expireAfter: 720h
  limits:
    cpu: "1000"
    memory: 1000Gi
  weight: 10
