apiVersion: v1
kind: Pod
metadata:
name: pod-jupyter-test
labels:
    app: pod-jupyter-test
spec:  # specification of the pod's contents
restartPolicy: Never
containers:
- name: pod-jupyter-test
    image: jupyterhub/jupyterhub
    ports:
    - containerPort: 8000
