name: Build Docker Images

on:
  pull_request:
    paths:
      - 'Dockerfile*'
  workflow_dispatch:

jobs:
  docker-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - name: base
            dockerfile: Dockerfile
          - name: matlab
            dockerfile: Dockerfile.matlab
          - name: gpu
            dockerfile: Dockerfile.gpu
          - name: gpu-matlab
            dockerfile: Dockerfile.gpu.matlab
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: images
          file: ${{ matrix.dockerfile }}
          push: false
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/dandihub:latest-${{ matrix.image.name }}
          cache-to: type=inline