name: Build Docker Images

on:
  pull_request:
    paths:
      - 'Dockerfile*'
  workflow_dispatch:

jobs:
  docker-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        file:
          - Dockerfile
          - Dockerfile.matlab
          - Dockerfile.gpu
          - Dockerfile.gpu.matlab
        tag:
          - latest
          - latest-matlab
          - latest-gpu
          - latest-gpu-matlab

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./images
          file: ./images/${{ matrix.file }}
          push: false
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_DANDIHUB_USERNAME }}/dandihub:${{ matrix.tag }}
          cache-to: type=inline