name: Build Docker Images

on:
  pull_request:
    paths:
      - 'Dockerfile*'
  workflow_dispatch:

jobs:
  docker-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockerfile:
          - { file: Dockerfile, tag: latest }
          - { file: Dockerfile.matlab, tag: latest-matlab }
          - { file: Dockerfile.gpu, tag: latest-gpu }
          - { file: Dockerfile.gpu.matlab, tag: latest-gpu-matlab }

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./images
          file: ./images/${{ matrix.dockerfile.file }}
          push: false
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_DANDIHUB_USERNAME }}/dandihub:${{ matrix.dockerfile.tag }}
          cache-to: type=inline